### ISSUE TITLE
Parameter Names

### ISSUE THREAD

**Issue by andrewpaulreeves** [andrewpaulreeves/soapy#20]
Some of the names of parameters are not very clear and are a simply an artifact of some earlier development. Perhaps these should be changed to something better @matthewtownson ?

Some which could be changed:

```python

sim
    filePrefix  -->  dataDir

tel
    obs      -->  obsDiam

wfs
    subapOversamp -->  fftOversamp

lgs
    lgsUplink -->  uplink
    lgsPupilDiam -->  pupilDiam
    
dm
    dmType   -->  type
    dmActs    -->  nActuators
    dmCond  -->  svdConditioning

sci
    oversamp   -->   fftOversamp

```

**Comment by matthewtownson** [comment]
They make sense, 2 suggestions:

I think `filePrefix` would be better as `simName`, as it's where stuff goes from a given set of simulations, rather than just one.

If you are changing actuators to be the number along one dimension, then I would include that in the parameter, so `dmActs` would go to `nxActuators` rather than `nActuators`.

**Comment by andrewpaulreeves** [comment]
Now complete
